### ISSUE TITLE
How to make the scale factor a default setting

### ISSUE THREAD

**Issue by BrahimDahmani** [josefernand/atom-scale-factor#1]
Awesome Packages !
But i have to set the scale factor each time i start Atom, how can i automatically set scale factor on atom start?

**Comment by josefernand** [comment]
Hi @BrahimDahmani thanks for your comment. Unfortunately, there is still no way to do that in the current version 0.1.1. But it's something that is on my mind too. I hope to have time to add some new features soon. If you want to help you are welcome!

**Comment by josefernand** [comment]
Hi @BrahimDahmani. The v0.2.0 is already released. You will see now in the package settings an option to "set the latest scale on start". It is unchecked by default, so please enable it.

**Comment by BrahimDahmani** [comment]
awesome, it's working perfectly! 

thnks bro
